CREATE SEQUENCE ADSEQ_TABLE;
DROP SEQUENCE ADSEQ_TABLE;


DROP TABLE ADMIN_TABLE;


CREATE TABLE ADMIN_TABLE(
     ADMINNAME VARCHAR2(50) PRIMARY KEY,
     ADMINPASSWORD VARCHAR2(200) NOT NULL,
     REGDATE DATE DEFAULT SYSDATE,
     UPDATEDATE DATE DEFAULT SYSDATE,
     LOGINFLAG NUMBER(10)
);

INSERT INTO ADMIN_TABLE(ADMINNAME, ADMINPASSWORD) VALUES('admin', 'admin');
DELETE FROM ADMIN_TABLE WHERE ADMINNAME = 'sun';
SELECT * FROM ADMIN_TABLE;