CREATE SEQUENCE LISTSEQ_TABLE;
DROP SEQUENCE LISTSEQ_TABLE;

CREATE TABLE LIST_TABLE(
     LISTNUM NUMBER(10, 0),
     CONTENTTYPEID VARCHAR2(200) ,
     FIRSTIMAGE VARCHAR2(300),
     TITLE VARCHAR2(200) ,
     CONTENTID VARCHAR2(200),
     USERNAME VARCHAR2(50)
);
DROP TABLE LIST_TABLE;

ALTER TABLE LIST_TABLE ADD CONSTRAINT LIST_TABLE_PK PRIMARY KEY(LISTNUM);

ALTER TABLE LIST_TABLE ADD CONSTRAINT FK_LIST_TABLE FOREIGN KEY(USERNAME)
REFERENCES MEMBER_TABLE(USERNAME);

INSERT INTO LIST_TABLE (LISTNUM, CONTENTTYPEID, FIRSTIMAGE, TITLE, CONTENTID, USERNAME) 
VALUES(LISTSEQ_TABLE.NEXTVAL, '1234566666', 'IMAGE','강화도', '89898989898', 'insun');
SELECT * FROM LIST_TABLE;